### ISSUE TITLE
Object Orientation of Codebase

### ISSUE THREAD

**Issue by isaac238** [WestheadJ/AppleMusic-to-Spotify-Converter-Python#8]
# Object Orientation of Codebase

## Issue
Currently the codebase is not object oriented (procedural) therefore, it is hard to maintain and lacks scalability.

## Feature Req and Suggestions

- Turn Spotipy interaction into its own class w/ Interfacing through methods
- Turn the Apple music processing code into its own object w/ attribute of URL that is inputted by user
- Keep the main file either as a procedural piece of code that uses classes Spotify interface + Apple music Interface or use a main object that is instantiated on name == main

**Comment by isaac238** [comment]
@WestheadJ pls remove bug label and keep enhancement, Cheers.

**Comment by WestheadJ** [comment]
> @WestheadJ pls remove bug label and keep enhancement, Cheers.

How come? You fixed the bug that I committed to the repository

**Comment by isaac238** [comment]
> > @WestheadJ pls remove bug label and keep enhancement, Cheers.
> 
> How come? You fixed the bug that I committed to the repository 

@WestheadJ 
Probably should have made a new issue for that now I think about it. The issue itself is an enhancement by updating the codebase to a new paradigm, not a bug-fix therefore not requiring the bug label. Instead the bug fix is identified by the fix: commit title.

**Comment by WestheadJ** [comment]
> > > @WestheadJ pls remove bug label and keep enhancement, Cheers.
> > 
> > How come? You fixed the bug that I committed to the repository 
> 
> @WestheadJ 
> Probably should have made a new issue for that now I think about it. The issue itself is an enhancement by updating the codebase to a new paradigm, not a bug-fix therefore not requiring the bug label. Instead the bug fix is identified by the fix: commit title.

Alright no worries then
